[FIO internal] imx8mm_evk: fix looking for undeclared setup_fec()
If CONFIG_FEC_MXC is undefined, setup_fec() is not declared. Remove
calling this function in preprocessor fixes a compiler warning [1].

[1]
board/freescale/imx8mm_evk/imx8mm_evk.c: In function ‘board_init’:
board/freescale/imx8mm_evk/imx8mm_evk.c:334:3: warning: implicit declaration of function ‘setup_fec’; did you mean ‘setup_i2c’? [-Wimplicit-function-declaration]
  334 |   setup_fec();
      |   ^~~~~~~~~

Signed-off-by: Oleksandr Suvorov <oleksandr.suvorov@foundries.io>
(cherry picked from commit e1de2acfe6eca39a128f974e923dd6e4bc41114f)